version: '3'

services:
  containera:
    container_name: containera
    build:
      context: .
      dockerfile: Dockerfile.containerA
    privileged: true
    networks:
      default:
      networkAB:
    extra_hosts:
      - "${DOMAINC}:${HOSTC}"
      - "${DOMAIND}:${HOSTD}"

  containerb:
    container_name: containerb
    build:
      context: .
      dockerfile: Dockerfile.containerB
    privileged: true
    networks:
      default:
      networkAB:
      networkBC:
    extra_hosts:
      - "${DOMAINC}:${HOSTC}"
      - "${DOMAIND}:${HOSTD}"

  containerc:
    container_name: containerc
    build:
      context: .
      dockerfile: Dockerfile.containerC
    privileged: true
    networks:
      default:
      networkBC:


  containerd:
    container_name: containerd
    build:
      context: .
      dockerfile: Dockerfile.containerD
    privileged: true
    networks:
      default:
      networkBC:


  containere:
    container_name: containere
    build:
      context: .
      dockerfile: Dockerfile.containerE
    privileged: true
    networks:
      default:
      networkAB:
    extra_hosts:
      - "${DOMAINC}:${HOSTC}"
      - "${DOMAIND}:${HOSTD}"

networks:
  networkAB:
    driver: bridge
  networkBC:
    driver: bridge
