FROM debian:stable-slim

RUN apt-get update 
RUN apt-get install -y iproute2 iputils-ping
RUN apt-get install -y tcpdump procps

# configure mock web server
RUN apt-get install -y python3 socat
RUN mkdir -p /var/www/html
RUN echo "containerC" > /var/www/html/container.txt

# copy the config and the entrypoint script
COPY common/config.sh /config.sh
COPY containerC/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]
