version: '3'

services:
  containera:
    container_name: containera
    build:
      context: .
      dockerfile: Dockerfile.containerA
    privileged: true
    networks:
      default:
      networkAB:
    extra_hosts:
      - "${DOMAINC}:${HOSTC}"

  containerb:
    container_name: containerb
    build:
      context: .
      dockerfile: Dockerfile.containerB
    privileged: true
    networks:
      default:
      networkAB:
      networkBC:

  containerc:
    container_name: containerc
    build:
      context: .
      dockerfile: Dockerfile.containerC
    privileged: true
    networks:
      default:
      networkBC:

  containerd:
    container_name: containerd
    build:
      context: .
      dockerfile: Dockerfile.containerD

networks:
  networkAB:
    driver: bridge
  networkBC:
    driver: bridge
