version: '3'

services:
  containera:
    container_name: containera
    build:
      dockerfile: Dockerfile.containerA
    privileged: true
    networks:
      default:
      networkAB:

  containerb:
    container_name: containerb
    build:
      dockerfile: Dockerfile.containerB
    privileged: true
    networks:
      default:
      networkAB:
      networkBC:

  containerc:
    container_name: containerc
    build:
      dockerfile: Dockerfile.containerC
    privileged: true
    networks:
      default:
      networkBC:
networks:
  networkAB:
    driver: bridge
  networkBC:
    driver: bridge
